# Copyright 2014 - Giovanni Simoni
#
# This file is part of PFT.
#
# PFT is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# PFT is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with PFT.  If not, see <http://www.gnu.org/licenses/>.
#
package App::PFT::Cmd::Init;

=head1 NAME

pft init

=head1 SYNOPSYS

pft init 

=cut

use strict;
use warnings;

use IO::File;
use File::Spec::Functions qw/catfile/;

use App::PFT::Struct::Tree;
use App::PFT::Struct::Conf qw/cfg_dump $SITE_HOME/;
use App::PFT::Util;

use Exporter qw/import/;
use feature qw/say/;

use Pod::Usage;
use Pod::Find qw/pod_where/;

use Getopt::Long qw/GetOptionsFromArray/;
Getopt::Long::Configure qw/bundling/;

my $HELP = <<"EOF";
This is the templates directory. Here you must have three files:

- page.html     -> Mandatory, template for pages
- entry.html    -> Mandatory, template for blog entries
- gen.html      -> Mandatory, template for generated pages (e.g. month)

Upon initialization, the three files are all symlinked to a fourth file
named `default.html`, which is created by $0 with sensible defaults.

If you wish to modify all the pages together you may change
`default.html`.

In order to modify a single template replace the symlinks with regular
template files.

The default can be restored by running `$0 init`: `default.html` is
regenerated if it is missing. Each of the other missing files is symlinked
to `default.html`.

EOF

my $HOME_TEXT = <<"EOF";

Welcome to this $0 site.

This page was auto-generated by the $0 Configurator.
EOF

sub main {
    GetOptions(
        'help|h!'       => sub {
            pod2usage
                -exitval => 1,
                -verbose => 2,
                -input => pod_where({-inc => 1}, __PACKAGE__)
            ;
        },
    );

    my $tree = App::PFT::Struct::Tree->new(basepath => '.');

    my $default = 'default.html';
    unless (-e $default) {
        say STDERR "Creating template $default";
        my $default_templ = IO::File->new(
            catfile($tree->dir_templates, $default),
            'w'
        );
        say $default_templ <App::PFT::Cmd::Init::DATA>;
        close App::PFT::Cmd::Init::DATA;
    }

    my $page = catfile($tree->dir_templates, 'page.html');
    App::PFT::Util::ln $default, $page, 1 unless -e $page;
    my $entry = catfile($tree->dir_templates, 'entry.html');
    App::PFT::Util::ln $default, $entry, 1 unless -e $entry;
    my $gen = catfile($tree->dir_templates, 'gen.html');
    App::PFT::Util::ln $default, $gen, 1 unless -e $gen;

    my $readme = catfile($tree->dir_templates, 'README');
    unless (-e $readme) {
        my $rf = IO::File->new($readme, 'w');
        print $rf $HELP;
    }

    unless ($tree->page(title => $SITE_HOME, -noinit => 1)->exists) {
        say STDERR "Creating default site home: $SITE_HOME";
        my $hf = $tree->page(
            title => $SITE_HOME,
            author => "$0 Configurator",
        )->file('a');
        print $hf $HOME_TEXT;
    }
}

1;

__DATA__

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=[% site.encoding %]">
  <title>[% site.title %] :: [% content.title %]</title>

    <style type="text/css">

        html {
            margin : 0;
            padding : 0;
            font-family : sans-serif;
            line-height : 1.5em;
        }

        body {
            margin : 0 auto 0;
            padding : 5em 5em 0;
            min-width : 40em;
            max-width : 50em;
        }

        h1,h2,h3,h4,h5,h6 {
            line-height : 1em;
        }

        div#title {
            text-align : center;
        }

        a a:link a:visited {
            color : cornflowerblue;
            text-decoration : none;
        }

        a:hover {
            color : #87aced;
        }

        .side {
            float : right;
        }

        div#sitemap {
            margin-top : 2em;
            width : 25%;
        }

        div#sitemap h1 {
            font-size : 1em;
        }

        h1#sitetitle {
            margin-bottom : 1em;
            border-bottom : 1px solid cornflowerblue;
        }

        div#pagetitle {
            margin : 2em 0 2em;
        }

        div#pagetitle h2 {
            font-size : 1em;
        }

        div#pagetitle h3 {
            font-size : 1em;
            display : inline;
        }

        div#content {
            font-family : serif;
            width : 65%;
        }

        div#content #title h1 {
            font-size : 2em;
        }

        div#content #text pre {
            overflow : auto;
            background : #ccc;
            padding : .5em;
        }

        div#content p img {
            max-width : 100%;
        }

        div#content h1,h2,h3,h4,h5,h6 { font-family : sans; }
        div#content h1 { font-size : 1.7em; }
        div#content h2 { font-size : 1.5em; }
        div#content h3 { font-size : 1.4em; }
        div#content h4 { font-size : 1.3em; }
        div#content h5 { font-size : 1.2em; }
        div#content h6 { font-size : 1.1em; }

        div#footer {
            color : silver;
            clear : right;
            margin-right : 0;
            margin-left : auto;
            font-size : .8em;
            text-align : left;
        }

    </style>
</head>

<body id="top">

<h1 id="sitetitle">[% site.title %]</h1>

<div id="sitemap" class="side">
  [% IF links.backlog %]
  <h1>Last 5 entries:</h1>
  <ul>
    [% FOREACH e = links.backlog; IF loop.count > 5 BREAK END %]
      <li>
        <a href="[% e.href %]">
          [% e.slug %]
        </a>
      </li>
    [% END %]
  </ul>
  [% END %]

  [% IF links.pages %]
  <h1>Pages:</h1>
  <ul>
    [% FOREACH p = links.pages %]
      <li><a href="[% p.href %]">[% p.slug %]</a></li>
    [% END %]
  </ul>
  [% END %]

  [% IF links.backlog %]
  <h1>Last 5 entries:</h1>
  <ul>
    [% FOREACH e = links.backlog; IF loop.count > 5 BREAK END %]
      <li>
        <a href="[% e.href %]">
          [% e.slug %]
        </a>
      </li>
    [% END %]
  </ul>
  [% END %]

  [% IF links.months %]
  <h1>Last 5 months:</h1>
  <ul>
    [% FOREACH m = links.months; IF loop.count > 5 BREAK END %]
      <li>
        <a href="[% m.href %]">[% m.slug %]</a>
      </li>
    [% END %]
  </ul>
  [% END %]

  [% IF links.tags %]
  <h1>All the tags</h1>
  <ul>
    [% FOREACH t = links.tags %]
      <li>
        <a href="[% t.href %]">[% t.slug %]</a>
      </li>
    [% END %]
  </ul>
  [% END %]

  [% IF (links.root || links.prev || links.next) %]
  <h1>Navigation:</h1>
  <ul>
    [% IF links.root %]
    <li id="root">
      Up: <a href="[% links.root.href %]">[% links.root.slug %]</a>
    </li>
    [% END %]

    [% IF links.prev %]
    <li id="prev">
      Prev: <a href="[% links.prev.href %]">[% links.prev.slug %]</a>
    </li>
    [% END %]

    [% IF links.next %]
    <li id="next">
      Next: <a href="[% links.next.href %]">[% links.next.slug %]</a>
    </li>
    [% END %]
  </ul>
  [% END %]

</div>

<div id="pagetitle">
  <h1>[% content.title %]</h1>
  [% IF content.date %]
  <h2>[% content.date.y %] / [% content.date.m %] / [% content.date.d %]</h2>
  [% END %]
  [% IF content.tags %]
  <h3>Tags:</h3>
  [%   FOREACH t = content.tags %] <a href="[% t.href %]">[% t.slug %]</a> [% END %]
  [% END %]
</div>

<div id="content">
  <div id="text">
    [% content.html %]

    [% IF links.related %]
    <ul>
      [% FOREACH l = links.related %]
        <li>[% l.date.y %] / [% l.date.m %] / [% l.date.d %]:
        <a href="[% l.href %]">[% l.slug %]</a></li>
      [% END %]
    </ul>
    [% END %]
  </div>
</div>

<div id="footer">
    <a href="#top">Back</a>
</div>

</body>
</html>
